### ISSUE TITLE
Some details about processing on different feature dimensions

### ISSUE THREAD

**Issue by FT115** [jbwang1997/CrossKD#1]
Great Work! I want to find out how can the teacher model process the different feature dimensions, i.e., the intermediate student features (mainly presented in the channel dimension). As far as I know, different channel dimensions may result in the teacher model not being able to perform forward propagation properly. Which part of the code reflects the processing of this part？
Looking forward to your reply very much！

**Comment by FT115** [comment]
![image](https://github.com/jbwang1997/CrossKD/assets/88318796/61ba3bc1-31f5-42c6-8426-f947069967f7)
From two functions (refused_teacher_head and align_scale) in crosskd_gfl.py, the intermediate features of the student model seem to be completely consistent in size with the intermediate features of the teacher model.
If this is the case, what should be done when the dimensions of the two are inconsistent?

**Comment by jbwang1997** [comment]
Thanks for your interest in this work.

So far, this project didn't support the situation when the channels of the teacher's detection head don't match the student's. Generally, the channels of teacher-student detection heads are the same attributing to FPN. If you have to handle this problem, you can add a small mapper (1x1 conv) to align the channels of the teacher-student features.

**Comment by FT115** [comment]
> Thanks for your interest in this work.
> 
> So far, this project didn't support the situation when the channels of the teacher's detection head don't match the student's. Generally, the channels of teacher-student detection heads are the same attributing to FPN. If you have to handle this problem, you can add a small mapper (1x1 conv) to align the channels of the teacher-student features.

Thank you for your reply! Based on your answer, which plan do you think is more reasonable: adjusting the teacher channels, adjusting the student channels, or adjusting both teacher and student. Does this 1x1 conv parameter need to be used for training? According to your understanding, have previous studies taken this into account?

**Comment by FT115** [comment]
> 
According to your approach, it seems that adjusting the student channels can better ensure the subsequent inference process.

**Comment by jbwang1997** [comment]
I prefer to adjust the student channels and simultaneously optimize the 1x1 conv in training.

Additionally, it may get better performance if we can directly adjust the channels of teacher-student detection head as the same.

**Comment by FT115** [comment]
> I prefer to adjust the student channels and simultaneously optimize the 1x1 conv in training.
> 
> Additionally, it may get better performance if we can directly adjust the channels of teacher-student detection head as the same.

Thank you for your reply and once again express my admiration for your work!
