### ISSUE TITLE
Possible ICCV2023 Violation

### ISSUE THREAD

**Issue by khurramHashmi** [jbwang1997/CrossKD#2]
Hi,

Congratulations on your impressive and insightful work in the field of object detection.

While browsing through your GitHub repository, I noticed that your README file mentions a paper being under review for ICCV 2023. I thought it might be worth mentioning that, according to ICCV's double-blind policy, which can be found [Here](https://iccv2023.thecvf.com/author.faqs-361800-2-20-18.php#:~:text=Are%20ICCV%202023%20Reviews%20Double,the%20names%20of%20the%20authors.), you may want to remove this information to maintain the anonymity of the submission process.

Wishing you all the best :).

**Comment by FishAndWasabi** [comment]
Hi,

Thanks for your kind advice! We have removed this information.

Best Wishes! 😊
