### ISSUE TITLE
Clarification about a part of the paper

### ISSUE THREAD

**Issue by Y-T-G** [jbwang1997/CrossKD#3]
Hey, great work. Probably the best paper on this subject so far. Discusses and compares with all the major previous works.

Just wanted to know what is meant by this part in the paper:

> Compared to directly closing the predictions between the teacher-student pair, CrossKD allows part of the student’s detection head to be only relative with detection losses, resulting in a better optimization towards ground-truth targets

Specifically the part about "to be only relative with detection losses". What does relative mean here and which "part of the student's detection head" is being relative with detection losses?

Thanks.

**Comment by jbwang1997** [comment]
Thanks for your interest.

In original prediction mimicking, the student head will be optimized according to both original detection losses and distillation losses. In CrossKD, we separate distillation losses to the cross-head branch. Consequently, the last convolution layers of the student only optimized according to detection losses, which is the meaning of "to be only relative with detection losses".

**Comment by Y-T-G** [comment]
I see. Makes sense. Thanks.
