### ISSUE TITLE
About  configuration of SwinT 

### ISSUE THREAD

**Issue by OrdinaryQin** [jbwang1997/CrossKD#4]
Thank you very much for your outstanding work, which has aroused great interest in me.
Could you please provide the name of the SwinT based crosskd related configuration file? Thank you for your help.

**Comment by jbwang1997** [comment]
Thanks for your interest. We will update the config and model ASAP. After updating, I will notify you in this issue.

**Comment by FishAndWasabi** [comment]
Hi,

We have updated the SwinT based config (in configs/crosskd/crosskd_r50_retinanet_swint_fpn_1x_coco.py) and checkpoint (in README). Thanks for getting in touch! 

Best Wishes! 😊
