### ISSUE TITLE
the log of FCOS

### ISSUE THREAD

**Issue by ShangGL123** [jbwang1997/CrossKD#9]
Thank you for your work. Could you please provide  log file of FCOS to verify the correctness of my experiment?

**Comment by jbwang1997** [comment]
Sorry for my late reply. You can find all log file at [here](https://drive.google.com/drive/folders/1M1qVfp1ETKKFIhK4CB8NqHrGYgbrVMeB).
For now, we miss the log file of only CrossKD FCOS. We will re-implement CrossKD FCOS later.
You can first refer to the log file of [CrossKD+PKD FCOS](https://drive.google.com/drive/folders/1SSJjGUXfXlY4IDQrvQeSICiHMMMqRv14).
